### ISSUE TITLE
Add a if statement

### ISSUE THREAD

**Issue by charlotte-pel** [dl4sits/BreizhCrops#16]
Add a if statement if csvfolder already exists:
`if not os.path.exists(self.csvfolder):`

https://github.com/TUM-LMF/BreizhCrops/blob/843aae8e6b2c8cbfa4eec08a1dc1ec87bd8c6fe4/breizhcrops/datasets/breizhcrops.py#L93

**Comment by MarcCoru** [comment]
Hmm the folder structure should already exist from 
https://github.com/TUM-LMF/BreizhCrops/blob/843aae8e6b2c8cbfa4eec08a1dc1ec87bd8c6fe4/breizhcrops/datasets/breizhcrops.py#L98

executed before the download csv script
https://github.com/TUM-LMF/BreizhCrops/blob/843aae8e6b2c8cbfa4eec08a1dc1ec87bd8c6fe4/breizhcrops/datasets/breizhcrops.py#L45

plus there are already a lot of if statements before the download csv function is executed.
https://github.com/TUM-LMF/BreizhCrops/blob/843aae8e6b2c8cbfa4eec08a1dc1ec87bd8c6fe4/breizhcrops/datasets/breizhcrops.py#L59

**Comment by MarcCoru** [comment]
Closing this for now

**Comment by charlotte-pel** [comment]
i guess in my case I already had the csv files on my computer (as I process them). So I only wanted to create the h5 file (without redownloading the csv files).
This case is indeed really specific to my situation.
