### ISSUE TITLE
some bugs for XX_Train and Evaluate Models

### ISSUE THREAD

**Issue by Luffy2Github** [dl4sits/BreizhCrops#27]
1.import models.transformer.Optim
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-20-608305f09f8d> in <module>
     12 from tqdm import tqdm
     13 import numpy as np
---> 14 import models.transformer.Optim

ModuleNotFoundError: No module named 'models.transformer.Optim'
-------------------------------------------------------------------------------

**Comment by maxzoll** [comment]
Hi @Luffy2Github,
also regarding the issues #25 and #26, all the outdated notebooks were removed. Instead, you can now check the Hands-on Tutorial on Time Series (https://colab.research.google.com/drive/1i0M_X5-ytFhF0NO-FjhKiqnraclSEIb0?usp=sharing) for a detailed data analysis and visual exploration.

**Comment by Luffy2Github** [comment]
Hi maxzoll,
 Thank you very much



dz1827002@smail.nju.edu.cn
 
From: maxzoll
Date: 2020-10-06 21:14
To: dl4sits/BreizhCrops
CC: Luffy2Github; Mention
Subject: Re: [dl4sits/BreizhCrops] some bugs for XX_Train and Evaluate Models (#27)
Hi @Luffy2Github,
also regarding the issues #25 and #26, all the outdated notebooks were removed. Instead, you can now check the Hands-on Tutorial on Time Series (https://colab.research.google.com/drive/1i0M_X5-ytFhF0NO-FjhKiqnraclSEIb0?usp=sharing) for a detailed data analysis and visual exploration.
